#NB Classifier

In [1]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [2]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast','Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [3]:
le = preprocessing.LabelEncoder()
w_e = le.fit_transform(weather)
t_e = le.fit_transform(temp)
p_e = le.fit_transform(play)
print(w_e)
print(t_e)
print(p_e)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [4]:
features = tuple(zip(w_e,t_e))
print(features)
print(p_e)

((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [5]:
model = MultinomialNB()
model.fit(features, p_e)

MultinomialNB()

1.5 Exercise: Manually calculate output for the following cases and compare it
with system’s output.
1.5.1 (1) Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?
1.5.2 (2) Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

In [6]:
# temp = hot -> 1, w = overcast -> 0
print(model.predict([[0,1]]))

[1]


In [7]:
# mild -> 0, sunny -> 2
print(model.predict([[2,0]]))

[1]


# IRIS
76<=Rollnumber<=100: #Task 1: Try the algo on Dataset2 - OneHotEncoding of features:
and Train test Division 75%-25% #Task 2: Apply algorithm on wine dataset - LabelEncoding of
features: and Train test Division 80%-20%

In [ ]:
import numpy as np
import pandas as pd
from pandas import read_csv
data2 = pd.read_csv('/content/drive/MyDrive/Dataset2.csv')
# data2 = np.array(data2)
print(data2)

In [ ]:
X = data2.iloc[:,:-1]
y = data2.iloc[:,-1:]
print(X)
print(y)

In [10]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
onehotencoder = OneHotEncoder()

In [11]:
ol = onehotencoder.fit_transform(X.Outlook.values.reshape(-1,1)).toarray()
tm = onehotencoder.fit_transform(X.Temp.values.reshape(-1,1)).toarray()
wd = onehotencoder.fit_transform(X.Wind.values.reshape(-1,1)).toarray()
hm = onehotencoder.fit_transform(X.Humidity.values.reshape(-1,1)).toarray()
# print(x)

In [ ]:
# features = tuple(zip(ol,tm,wd,hm))
print(X)
dfOneHot = pd.DataFrame(ol, columns = ["Outlook"+str(int(i)) for i in range(0,3)])
X = pd.concat([X, dfOneHot], axis=1) 
X = X.drop(["Outlook"], axis=1)
dfOneHot = pd.DataFrame(ol, columns = ["Temp"+str(int(i)) for i in range(0,3)])
X = pd.concat([X, dfOneHot], axis=1) 
X = X.drop(['Temp'], axis=1)
dfOneHot = pd.DataFrame(ol, columns = ["Wind"+str(int(i)) for i in range(0,3)])
X = pd.concat([X, dfOneHot], axis=1) 
X = X.drop(['Wind'], axis=1)
dfOneHot = pd.DataFrame(ol, columns = ["Humidity"+str(int(i)) for i in range(0,3)])
X = pd.concat([X, dfOneHot], axis=1) 
X = X.drop(['Humidity'], axis=1)
print(X.head())

In [ ]:
print(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
print(X_train)

In [ ]:
model = MultinomialNB()
model.fit(X_train, y_train)

In [17]:
pred = model.predict(X_test)

In [ ]:
print(pred)
print(y_test)

# #Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 80%-20%

In [ ]:
from sklearn import datasets
wine_dataset = datasets.load_wine()
print(wine_dataset.feature_names)
print(wine_dataset.data)

In [20]:
data_train, data_test, target_train, target_test = train_test_split(wine_dataset.data, wine_dataset.target, test_size = 0.20, random_state = 5)

In [ ]:
model = MultinomialNB()
model.fit(data_train,target_train)

In [22]:
y = model.predict(data_test)
i = 0
correct = 0
for pred in y:
  if pred == target_test[i]:
    correct = correct + 1
  i = i + 1
print("Accuracy : " , (correct*100)/i)

Accuracy :  77.77777777777777
